### ISSUE TITLE
zkspring-security module is incompatible with Spring security 4.x

### ISSUE THREAD

**Issue by Mogztter** [zkoss/zkspring#26]
Here is the migration guide: http://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-xml.html

I've done some changes but I don't know how to build the project. There's an Ant's build.xml at the root of the project but also a pom.xml inside each module and external lib in `dist/lib`. Do you have a README or a contributing guide ?

**Comment by vikulin** [comment]
Any updates here?

**Comment by cor3000** [comment]
zkspring-security 4.0.0 is now compatible with spring security 4/5
(however some features where removed, see [release notes](https://github.com/zkoss/zkspring/blob/4.0.0/zkdoc/release-note))
