### ISSUE TITLE
zkspring in Maven

### ISSUE THREAD

**Issue by connollyst** [zkoss/zkspring#29]
Are these artifacts available through [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22zkspring-webflow%22), or only through [ZK's own repository](http://mavensync.zkoss.org/maven2/org/zkoss/zk/)? If only in ZK's repo, any reason for that?

Thanks!
Sean

**Comment by hawkchen** [comment]
The latest version is only available in zk repository. I think it's easier for us to manage artifacts.
